import { Box, Container, Paper, Stack, Typography } from "@mui/material";

export default function ChatMessage({ text, type }) {
  return (
    <Container disableGutters>
      <Stack direction={type === "chatPrompt" ? "row-reverse" : "row"}>
        <Paper
          className={type}
          elevation={5}
          sx={{ pl: 2, pr: 2, pt: 1, pb: 1, borderRadius: 3 }}
        >
          <Typography className={type} variant="p">
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          dddddd
          </Typography>
        </Paper>
      </Stack>
    </Container>
  );
}
